DROP TABLE IF EXISTS m_account;

CREATE TABLE `m_account` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_type_id` BIGINT UNSIGNED DEFAULT NULL,
  `name` VARCHAR(64),
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`account_type_id`) REFERENCES `m_account_type` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

